# Generated by Django 4.2.3 on 2023-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.TextField()),
                ("district", models.TextField()),
                ("muncipality", models.TextField()),
                ("project_title", models.TextField()),
                ("project_status", models.TextField()),
                ("donor", models.TextField()),
                ("executing_agency", models.TextField()),
                ("implementing_partner", models.TextField()),
                ("counterpart_ministry", models.TextField()),
                ("type_of_assistance", models.TextField()),
                ("budget_type", models.TextField()),
                ("humanitarian", models.TextField()),
                ("sector", models.TextField()),
                ("agreement_date", models.DateField()),
                ("commitments", models.IntegerField()),
                ("disbursement", models.IntegerField()),
            ],
        ),
    ]
